# Components defined here are required to be kept in sync with hack/gen-versions/calico.go.tpl
title: release-v3.31
components:
  libcalico-go:
    version: release-v3.31
  typha:
    version: release-v3.31
  calico/node:
    version: release-v3.31
  calico/cni:
    version: release-v3.31
  calico/node-windows:
    version: release-v3.31
  calico/cni-windows:
    version: release-v3.31
  calico/kube-controllers:
    version: release-v3.31
  calico/goldmane:
    version: release-v3.31
  flexvol:
    version: release-v3.31
  calico/apiserver:
    version: release-v3.31
  calico/csi:
    version: release-v3.31
  csi-node-driver-registrar:
    version: release-v3.31
  key-cert-provisioner:
    version: release-v3.31
  calico/whisker:
    version: release-v3.31
  calico/whisker-backend:
    version: release-v3.31
  calico/envoy-gateway:
    version: release-v3.31
  calico/envoy-proxy:
    version: release-v3.31
  calico/envoy-ratelimit:
    version: release-v3.31
  calico/guardian:
    version: release-v3.31

